name: C++ with CMake CI

on: [push, pull_request]

jobs:
  UniquePtr:
    runs-on: ubuntu-20.04
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: mkdir homework/unique_ptr/build 
      run: mkdir homework/unique_ptr/build
    - name: Compile
      working-directory: homework/unique_ptr/build
      run: |
        cmake ..
        make
    - name: Run test 
      working-directory: homework/unique_ptr/build
      run: ctest -V
    - name: Run Valgrind
      working-directory: homework/unique_ptr/build
      run: |
          sudo apt-get update -y
          sudo apt-get install -y valgrind
          valgrind --leak-check=yes ./UniquePtr-ut 
